services:
  # 1. 데이터 티어 (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

  # 2. 애플리케이션 티어 (Go API)
  app:
    container_name: my-go-api
    restart: always
    build: . 
    environment:
      DB_SOURCE: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    depends_on:
      - db

  # 3. 프레젠테이션 티어 (Nginx)
  web:
    container_name: my-nginx-web
    restart: always
    # 'Dockerfile.nginx' 파일을 사용해 빌드
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres-data: